apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: app-architecture-sample-restaurant-service
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: app-architecture-sample
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/vmware-jaret/app-architecture-sample-restaurant.git
      ref:
        branch: main
  serviceClaims:
    - name: postgres-db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: restaurant-database-claim